feat: allow signing/encrypting Buffer payloads
panva/paseto pull request #15
Opened 2021-02-23 15:59 UTC by lhchavez

The reference PHP implementation[1] allows "to store arbitrary binary
data in a PASETO, by invoking the Protocol classes directly". This
change adds support for the {V1,V2}.{sign,encrypt} functions to be able
to receive Buffers as the payload. It also adds a new option (`{ buffer:
true }`) to the {V1,V2}.{verify,decrypt} functions so that they return a
Buffer instead of a parsed token, for symmetry.

1: https://github.com/paragonie/paseto/tree/master/docs/02-PHP-Library#using-the-protocol-directly

2021-02-23 20:31 UTC, panva requested changes

2021-02-23 20:31 UTC, panva commented on types/index.d.ts
> +        payload: object | Buffer | string,
```suggestion
        payload: object | Buffer,
```

2021-02-23 20:31 UTC, panva commented on types/index.d.ts
> +        payload: object | Buffer | string,
```suggestion
        payload: object | Buffer,
```

2021-02-23 20:31 UTC, panva commented on types/index.d.ts
> +     * })()
please remove this example. the addition of the API is enough.

2021-02-23 20:31 UTC, panva commented on types/index.d.ts
> +     * })()
please remove this example. the addition of the API is enough.

2021-02-23 20:31 UTC, panva commented on types/index.d.ts
> +        payload: object | Buffer | string,
```suggestion
        payload: object | Buffer,
```

2021-02-23 20:31 UTC, panva commented on types/index.d.ts
> +        payload: object | Buffer | string,
```suggestion
        payload: object | Buffer,
```

2021-02-23 20:31 UTC, panva commented on types/index.d.ts
> +     * })()
please remove this example. the addition of the API is enough.

2021-02-23 20:31 UTC, panva commented on types/index.d.ts
> +     * })()
please remove this example. the addition of the API is enough.

2021-02-23 20:31 UTC, panva commented on README.md
> +  }
please remove this example. the addition of the API is enough.

2021-02-23 20:31 UTC, panva commented on README.md
> +  }
please remove this example. the addition of the API is enough.

2021-02-23 20:31 UTC, panva commented on README.md
> +  }
please remove this example. the addition of the API is enough.

2021-02-23 20:31 UTC, panva commented on README.md
> +  }
please remove this example. the addition of the API is enough.

2021-02-23 23:43 UTC, panva commented
@lhchavez sorry for the intrusion, I've decided to drop v2.local support to avoid the massive libsodium dependency. Can you take that into consideration and rebase this PR?

2021-02-24 00:01 UTC, lhchavez commented
> @lhchavez sorry for the intrusion, I've decided to drop v2.local support to avoid the massive libsodium dependency. Can you take that into consideration and rebase this PR?

whew! not using that, so a bullet was dodged!

sure thing gimme a few minutes

2021-02-24 00:18 UTC, lhchavez commented
> > @lhchavez sorry for the intrusion, I've decided to drop v2.local support to avoid the massive libsodium dependency. Can you take that into consideration and rebase this PR?
> 
> whew! not using that, so a bullet was dodged!
> 
> sure thing gimme a few minutes

done!

2021-02-24 07:21 UTC, panva approved these changes

2021-02-24 07:42 UTC, merged